package com.memorial.app.ui.theme

import androidx.compose.ui.graphics.Color

// Material baseline (kept for compatibility)
val md_theme_light_primary = Color(0xFF6B5CE7)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFEDE9FE)
val md_theme_light_onPrimaryContainer = Color(0xFF1A1A2E)
val md_theme_light_secondary = Color(0xFF7A6A5D)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF5EDE6)
val md_theme_light_onSecondaryContainer = Color(0xFF3E3229)
val md_theme_light_tertiary = Color(0xFF5B6B5B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE8F0E8)
val md_theme_light_onTertiaryContainer = Color(0xFF2D3A2D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8F7FC)
val md_theme_light_onBackground = Color(0xFF1C1B1A)
val md_theme_light_surface = Color(0xFFFDFBF8)
val md_theme_light_onSurface = Color(0xFF1C1B1A)
val md_theme_light_surfaceVariant = Color(0xFFECE5DE)
val md_theme_light_onSurfaceVariant = Color(0xFF4E4540)
val md_theme_light_outline = Color(0xFF81756E)
val md_theme_light_inverseOnSurface = Color(0xFFF4F0ED)
val md_theme_light_inverseSurface = Color(0xFF31302F)
val md_theme_light_inversePrimary = Color(0xFFD5C4B5)
val md_theme_light_surfaceTint = Color(0xFF6B5CE7)

// Memora Brand Colors
val PrimaryPurple = Color(0xFF6B5CE7)
val PrimaryPurpleLight = Color(0xFF9B8AF3)
val PrimaryPurpleDark = Color(0xFF4A3FB5)
val BackgroundWarm = Color(0xFFF8F7FC)
val CardSurface = Color(0xFFFFFFFF)
val TextPrimary = Color(0xFF1A1A2E)
val TextSecondary = Color(0xFF6B6B7B)
val TextMuted = Color(0xFF9A9AA6)
val DividerLight = Color(0xFFE5E5EB)

// Status colors
val StatusDraft = Color(0xFF9CA3AF)
val StatusDraftBg = Color(0xFFF3F4F6)
val StatusUpload = Color(0xFF6B5CE7)
val StatusUploadBg = Color(0xFFEDE9FE)
val StatusGenerating = Color(0xFFF59E0B)
val StatusGeneratingBg = Color(0xFFFEF3C7)
val StatusPreview = Color(0xFF10B981)
val StatusPreviewBg = Color(0xFFD1FAE5)
val StatusPurchased = Color(0xFFF97316)
val StatusPurchasedBg = Color(0xFFFFEDD5)
val StatusCompleted = Color(0xFF3B82F6)
val StatusCompletedBg = Color(0xFFDBEAFE)
val StatusFailed = Color(0xFFEF4444)
val StatusFailedBg = Color(0xFFFEE2E2)

// Trust & Accent
val TrustGreen = Color(0xFF10B981)
val WarmCream = Color(0xFFFDF6E3)
val SoftRose = Color(0xFFFCE7F3)
