package com.memorial.app.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF6B5B4F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF2ECE6)
val md_theme_light_onPrimaryContainer = Color(0xFF3E3229)
val md_theme_light_secondary = Color(0xFF7A6A5D)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF5EDE6)
val md_theme_light_onSecondaryContainer = Color(0xFF3E3229)
val md_theme_light_tertiary = Color(0xFF5B6B5B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE8F0E8)
val md_theme_light_onTertiaryContainer = Color(0xFF2D3A2D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFBF8)
val md_theme_light_onBackground = Color(0xFF1C1B1A)
val md_theme_light_surface = Color(0xFFFDFBF8)
val md_theme_light_onSurface = Color(0xFF1C1B1A)
val md_theme_light_surfaceVariant = Color(0xFFECE5DE)
val md_theme_light_onSurfaceVariant = Color(0xFF4E4540)
val md_theme_light_outline = Color(0xFF81756E)
val md_theme_light_inverseOnSurface = Color(0xFFF4F0ED)
val md_theme_light_inverseSurface = Color(0xFF31302F)
val md_theme_light_inversePrimary = Color(0xFFD5C4B5)
val md_theme_light_surfaceTint = Color(0xFF6B5B4F)
