package com.memorial.app.ui.theme

import androidx.compose.ui.graphics.Color

// Material baseline (kept for compatibility)
val md_theme_light_primary = Color(0xFF2D5F3F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE8F0E8)
val md_theme_light_onPrimaryContainer = Color(0xFF1C2418)
val md_theme_light_secondary = Color(0xFF5A6B54)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEEF2EB)
val md_theme_light_onSecondaryContainer = Color(0xFF2D3A2D)
val md_theme_light_tertiary = Color(0xFF8B7355)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF5F0E8)
val md_theme_light_onTertiaryContainer = Color(0xFF3E3229)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFAF7)
val md_theme_light_onBackground = Color(0xFF1C1B1A)
val md_theme_light_surface = Color(0xFFFDFCF8)
val md_theme_light_onSurface = Color(0xFF1C1B1A)
val md_theme_light_surfaceVariant = Color(0xFFEBEFE8)
val md_theme_light_onSurfaceVariant = Color(0xFF4A5548)
val md_theme_light_outline = Color(0xFFD5DDD0)
val md_theme_light_inverseOnSurface = Color(0xFFF4F0ED)
val md_theme_light_inverseSurface = Color(0xFF2A2E28)
val md_theme_light_inversePrimary = Color(0xFFB8D4B8)
val md_theme_light_surfaceTint = Color(0xFF2D5F3F)

// Memora Brand Colors
val PrimaryGreen = Color(0xFF2D5F3F)
val PrimaryGreenLight = Color(0xFF6BAF7A)
val PrimaryGreenDark = Color(0xFF1C3A2A)
val BackgroundWarm = Color(0xFFFAFAF7)
val CardSurface = Color(0xFFFFFFFF)
val TextPrimary = Color(0xFF1C2418)
val TextSecondary = Color(0xFF5A6B54)
val TextMuted = Color(0xFF8B9A84)
val DividerLight = Color(0xFFEBEFE8)

// Status colors
val StatusDraftBg = Color(0xFFF0F0F0)
val StatusDraft = Color(0xFF999999)
val StatusUploadBg = Color(0xFFE8F0E8)
val StatusUpload = Color(0xFF2D5F3F)
val StatusGenerating = Color(0xFFF59E0B)
val StatusGeneratingBg = Color(0xFFFEF3C7)
val StatusPreviewBg = Color(0xFFD8ECD8)
val StatusPreview = Color(0xFF3A7D4F)
val StatusPurchasedBg = Color(0xFFF5F0E0)
val StatusPurchased = Color(0xFFB8860B)
val StatusCompletedBg = Color(0xFFD4E8D4)
val StatusCompleted = Color(0xFF2D5F3F)
val StatusFailedBg = Color(0xFFFFE2E2)
val StatusFailed = Color(0xFFEF4444)

// Trust & Accent
val TrustGreen = Color(0xFF2D5F3F)
val WarmCream = Color(0xFFF5F0E8)
